import Logo from './favicon.ico';
import Search from './search.png'
import DownLoad from './download.png'
import Avatar from './avatar.png'
import Alert from './alert.png'
import Down from './down.png'
import Language from './language.png'
import Divider from './divider.png'
import Night from './night.png'

import OverView from './overview.png'
import Fiat from './fiat.png'
import Margin from './margin.png'
import Futures from './futures.png'
import Options from './options.png'
import Trading from './trading.png'
import Earn from './earn.png'
import Funding from './funding.png'
import Binance from './Binance.png'
import Tokocrypto from './Tokocrypto.png'
import Transaction from './transaction.png'
import Account from './account.png'
import Verification from './verification.png'

export { Logo, Search, DownLoad, Avatar, Alert, Down, Language, Divider, Night, OverView, Fiat, Margin, Futures, Options, Trading, Earn, Funding, Binance, Tokocrypto, Transaction, Account, Verification };