import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Logo } from '@/public'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Transaction history - Wallet - Binance',
  description: 'Generated by create next app',
  icons: [Logo.src],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
